/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POSTTEST5;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Simbolon-PC
 */
public class TabelPelanggan extends javax.swing.JFrame {
    private DefaultTableModel model;

    /**
     * Creates new form TabelKegiatan
     */
    public TabelPelanggan() {
        initComponents();
    }
public void InitTable(){
    model = new DefaultTableModel();
    model.addColumn("Nama");
    model.addColumn("No. Telpon");
    model.addColumn("Kota Asal");
    jTable1.setModel(model);
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_Nama = new javax.swing.JTextField();
        txt_NoHP = new javax.swing.JTextField();
        btn_Tambah = new javax.swing.JButton();
        btn_Ulangi = new javax.swing.JButton();
        btn_Bersihkan = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        btn_Update = new javax.swing.JButton();
        btn_Hapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_Simpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Keluar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(45, 115, 255));

        jPanel2.setBackground(new java.awt.Color(86, 142, 255));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tabel Pelanggan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(179, 179, 179))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(86, 142, 255));

        txt_Nama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_NamaCaretUpdate(evt);
            }
        });
        txt_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NamaActionPerformed(evt);
            }
        });

        txt_NoHP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_NoHPCaretUpdate(evt);
            }
        });
        txt_NoHP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NoHPKeyPressed(evt);
            }
        });

        btn_Tambah.setBackground(Color.getHSBColor(45,115,255));
        btn_Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Create.png"))); // NOI18N
        btn_Tambah.setText("Tambah");
        btn_Tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_TambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_TambahMouseExited(evt);
            }
        });
        btn_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahActionPerformed(evt);
            }
        });

        btn_Ulangi.setBackground(Color.getHSBColor(45,115,255));
        btn_Ulangi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/refresh.png"))); // NOI18N
        btn_Ulangi.setText("Ulangi");
        btn_Ulangi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_UlangiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_UlangiMouseExited(evt);
            }
        });
        btn_Ulangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UlangiActionPerformed(evt);
            }
        });

        btn_Bersihkan.setBackground(Color.getHSBColor(45,115,255));
        btn_Bersihkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Trash.png"))); // NOI18N
        btn_Bersihkan.setText("Bersihkan Tabel");
        btn_Bersihkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_BersihkanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_BersihkanMouseExited(evt);
            }
        });
        btn_Bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BersihkanActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(Color.getHSBColor(655,675,725));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samarinda", "Berau", "Balikpapan", "Bontang" }));

        btn_Update.setBackground(Color.getHSBColor(45,115,255));
        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Update.png"))); // NOI18N
        btn_Update.setText("Update");
        btn_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_UpdateMouseExited(evt);
            }
        });
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_Hapus.setBackground(Color.getHSBColor(45,115,255));
        btn_Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Erase.png"))); // NOI18N
        btn_Hapus.setText("Hapus");
        btn_Hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HapusMouseExited(evt);
            }
        });
        btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kota Asal");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. Telepon");

        btn_Simpan.setBackground(Color.getHSBColor(45,115,255));
        btn_Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Save.png"))); // NOI18N
        btn_Simpan.setText("Simpan");
        btn_Simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SimpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SimpanMouseExited(evt);
            }
        });
        btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimpanActionPerformed(evt);
            }
        });

        jTable1.setBackground(Color.getHSBColor(45,115,255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btn_Keluar.setBackground(Color.getHSBColor(45,115,255));
        btn_Keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/sign-out.png"))); // NOI18N
        btn_Keluar.setText("Keluar");
        btn_Keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_KeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_KeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_KeluarMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("(*wajib diisi)");

        jLabel14.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("(*format angka dan wajib diisi)");

        jLabel16.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("(*Ditekan aja dulu)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btn_Tambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Hapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Ulangi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_NoHP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Nama, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btn_Bersihkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(btn_Keluar)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Update)
                            .addComponent(btn_Simpan)
                            .addComponent(btn_Hapus)
                            .addComponent(btn_Ulangi)
                            .addComponent(btn_Tambah))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Bersihkan)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Keluar)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        InitTable();
    }//GEN-LAST:event_formComponentShown

    private void btn_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahActionPerformed
        txt_Nama.setEnabled(true);
        txt_NoHP.setEnabled(true);
        btn_Bersihkan.setEnabled(true);
        btn_Hapus.setEnabled(true);
//        btn_Simpan.setEnabled(true);
        btn_Ulangi.setEnabled(true);
        btn_Update.setEnabled(true);
        jComboBox1.setEnabled(true);
        txt_Nama.requestFocus();
    }//GEN-LAST:event_btn_TambahActionPerformed

    private void btn_BersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BersihkanActionPerformed
        int pilih1 = JOptionPane.showConfirmDialog(this, "Ingin Membersihkan Seluruh Data Di Tabel?","Confirm Hapus",JOptionPane.YES_OPTION);
        
        if(pilih1==JOptionPane.YES_OPTION){
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            txt_Nama.requestFocus();
        }
        
        
        
    }//GEN-LAST:event_btn_BersihkanActionPerformed

    private void btn_UlangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UlangiActionPerformed
        txt_NoHP.setText("");
        txt_Nama.setText("");
        txt_Nama.requestFocus();
        
        
    }//GEN-LAST:event_btn_UlangiActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        int baris = jTable1.getSelectedRow();
        try {
            jTable1.setValueAt(txt_Nama.getText(), baris, 0);
            jTable1.setValueAt(txt_NoHP.getText(), baris, 1);
            jTable1.setValueAt(jComboBox1.getSelectedItem(), baris, 2);
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Update");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Maaf, Silahkan Pilih Data Yang Ingin Diupdate Terlebih Dahulu");
        }

    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusActionPerformed
        int pilih = JOptionPane.showConfirmDialog(this, "Ingin Menghapus Data?","Confirm Hapus",JOptionPane.YES_OPTION);
//        int pilih = JOptionPane.showConfirmDialog(this, "Ingin Hapus","Confirm Hapus",JOptionPane.INFORMATION_MESSAGE,3);
        
        if(pilih==JOptionPane.YES_OPTION){
            try {
                int baris = jTable1.getSelectedRow();
                model.removeRow(baris);
                JOptionPane.showMessageDialog(this, "Data Dengan"+"\nNama : "+txt_Nama.getText()+"\nNo. Telepon : "+txt_NoHP.getText()+"\nKota Asal : "+jComboBox1.getSelectedItem()+"\nBerhasil Dihapus");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Tidak Ada Data Yang Dipilih Untuk Dihapus");
            }        
        }
    }//GEN-LAST:event_btn_HapusActionPerformed

    private void txt_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NamaActionPerformed
        
    }//GEN-LAST:event_txt_NamaActionPerformed

    private void btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimpanActionPerformed
        Object[] data = new Object[3];
        data[0] = txt_Nama.getText();
        data[1] = txt_NoHP.getText();
        data[2] = jComboBox1.getSelectedItem().toString();
        
        model.addRow(data);
    }//GEN-LAST:event_btn_SimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.getSelectedRow();
        
        String nama_edit = jTable1.getValueAt(baris, 0).toString();
        String nohp_edit = jTable1.getValueAt(baris, 1).toString();
        String angkatan_edit = jTable1.getValueAt(baris, 2).toString();
        
        txt_Nama.setText(nama_edit);
        txt_NoHP.setText(nohp_edit);
        jComboBox1.setSelectedItem(angkatan_edit);
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txt_Nama.setEnabled(false);
        txt_NoHP.setEnabled(false);
        btn_Bersihkan.setEnabled(false);
        btn_Hapus.setEnabled(false);
        btn_Simpan.setEnabled(false);
        btn_Ulangi.setEnabled(false);
        btn_Update.setEnabled(false);
        jComboBox1.setEnabled(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void txt_NoHPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NoHPKeyPressed
        txt_NoHP.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
            char karakter1 = e.getKeyChar();
            if(!((karakter1 >= '0') && (karakter1 <= '9')) || (karakter1 == '\b')){
                e.consume();
            }
            }
            
}); 
    }//GEN-LAST:event_txt_NoHPKeyPressed

    private void txt_NoHPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_NoHPCaretUpdate
        if (txt_NoHP.getText().length()== 0 ||  txt_Nama.getText().length()== 0){
            btn_Simpan.setEnabled(false);
        }
        else{
            btn_Simpan.setEnabled(true);
        }
    }//GEN-LAST:event_txt_NoHPCaretUpdate

    private void txt_NamaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_NamaCaretUpdate
         if (txt_NoHP.getText().length()== 0 ||  txt_Nama.getText().length()== 0){
            btn_Simpan.setEnabled(false);
        }
        else{
            btn_Simpan.setEnabled(true);
        }
    }//GEN-LAST:event_txt_NamaCaretUpdate

    private void btn_KeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_KeluarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_KeluarMouseClicked

    private void btn_SimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SimpanMouseEntered
        if(txt_NoHP.getText().length()!= 0 &&  txt_Nama.getText().length()!= 0){
//            btn_Simpan.setBackground(Color.getHSBColor(240,240,240));
            btn_Simpan.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_btn_SimpanMouseEntered

    private void btn_SimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SimpanMouseExited
        if(txt_NoHP.getText().length()!= 0 &&  txt_Nama.getText().length()!= 0){
        btn_Simpan.setBackground(Color.getHSBColor(45,115,255));
        }
    }//GEN-LAST:event_btn_SimpanMouseExited

    private void btn_TambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TambahMouseEntered
//        btn_Tambah.setBackground(Color.getHSBColor(65,75,115));
//        btn_Tambah.setBackground(Color.getHSBColor(25,175,215));
        btn_Tambah.setBackground(Color.getHSBColor(655,675,725));
    }//GEN-LAST:event_btn_TambahMouseEntered

    private void btn_TambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TambahMouseExited
        btn_Tambah.setBackground(Color.getHSBColor(45,115,255));
    }//GEN-LAST:event_btn_TambahMouseExited

    private void btn_UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateMouseEntered
//            btn_Simpan.setBackground(Color.getHSBColor(240,240,240));
            btn_Update.setBackground(Color.getHSBColor(655,675,725));
        
    }//GEN-LAST:event_btn_UpdateMouseEntered

    private void btn_UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateMouseExited
        btn_Update.setBackground(Color.getHSBColor(45,115,255));
    }//GEN-LAST:event_btn_UpdateMouseExited

    private void btn_HapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HapusMouseEntered
        btn_Hapus.setBackground(Color.getHSBColor(255,275,115));
    }//GEN-LAST:event_btn_HapusMouseEntered

    private void btn_HapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HapusMouseExited
        btn_Hapus.setBackground(Color.getHSBColor(45,115,255));
    }//GEN-LAST:event_btn_HapusMouseExited

    private void btn_UlangiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UlangiMouseEntered
//        btn_Ulangi.setBackground(Color.getHSBColor(655,275,425));
        btn_Ulangi.setBackground(Color.getHSBColor(655,675,725));
    }//GEN-LAST:event_btn_UlangiMouseEntered

    private void btn_UlangiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UlangiMouseExited
        btn_Ulangi.setBackground(Color.getHSBColor(45,115,255));
    }//GEN-LAST:event_btn_UlangiMouseExited

    private void btn_BersihkanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BersihkanMouseEntered
        btn_Bersihkan.setBackground(Color.green);
    }//GEN-LAST:event_btn_BersihkanMouseEntered

    private void btn_BersihkanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BersihkanMouseExited
        btn_Bersihkan.setBackground(Color.getHSBColor(45,115,255));
    }//GEN-LAST:event_btn_BersihkanMouseExited

    private void btn_KeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_KeluarMouseEntered
        btn_Keluar.setBackground(Color.getHSBColor(75,225,55));
    }//GEN-LAST:event_btn_KeluarMouseEntered

    private void btn_KeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_KeluarMouseExited
        btn_Keluar.setBackground(Color.getHSBColor(45,115,255));
    }//GEN-LAST:event_btn_KeluarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Bersihkan;
    private javax.swing.JButton btn_Hapus;
    private javax.swing.JButton btn_Keluar;
    private javax.swing.JButton btn_Simpan;
    private javax.swing.JButton btn_Tambah;
    private javax.swing.JButton btn_Ulangi;
    private javax.swing.JButton btn_Update;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_Nama;
    private javax.swing.JTextField txt_NoHP;
    // End of variables declaration//GEN-END:variables
}
