/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POSTTEST3;

/**
 *
 * @author Simbolon-PC
 */
public class LatihanBorderLayout extends javax.swing.JFrame {

    /**
     * Creates new form LatihanBorderLayout
     */
    public LatihanBorderLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTengah = new javax.swing.JPanel();
        pHome = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pProfil = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pGaleri = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pInformasi = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pAbout = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jAtas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        bHome = new javax.swing.JButton();
        bProfil = new javax.swing.JButton();
        bGaleri = new javax.swing.JButton();
        bInformasi = new javax.swing.JButton();
        bAbout = new javax.swing.JButton();
        jBawah = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jKanan = new javax.swing.JPanel();
        jKiri = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU UTAMA");
        setLocation(new java.awt.Point(250, 40));
        setUndecorated(true);

        jTengah.setBackground(new java.awt.Color(204, 255, 204));
        jTengah.setLayout(new java.awt.CardLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POSTTEST3/f981c959699f2a6e7a90f058ae1f96f68fdcbf36010510141808a9b8cf16280f.jpg"))); // NOI18N

        javax.swing.GroupLayout pHomeLayout = new javax.swing.GroupLayout(pHome);
        pHome.setLayout(pHomeLayout);
        pHomeLayout.setHorizontalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
            .addGroup(pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 815, Short.MAX_VALUE))
        );
        pHomeLayout.setVerticalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 578, Short.MAX_VALUE))
        );

        jTengah.add(pHome, "card2");

        jLabel8.setText("PROFIL");

        javax.swing.GroupLayout pProfilLayout = new javax.swing.GroupLayout(pProfil);
        pProfil.setLayout(pProfilLayout);
        pProfilLayout.setHorizontalGroup(
            pProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProfilLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel8)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        pProfilLayout.setVerticalGroup(
            pProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProfilLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel8)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        jTengah.add(pProfil, "card3");

        jLabel9.setText("GALERI");

        javax.swing.GroupLayout pGaleriLayout = new javax.swing.GroupLayout(pGaleri);
        pGaleri.setLayout(pGaleriLayout);
        pGaleriLayout.setHorizontalGroup(
            pGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGaleriLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel9)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        pGaleriLayout.setVerticalGroup(
            pGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGaleriLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel9)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        jTengah.add(pGaleri, "card4");

        jLabel10.setText("INFORMASI");

        javax.swing.GroupLayout pInformasiLayout = new javax.swing.GroupLayout(pInformasi);
        pInformasi.setLayout(pInformasiLayout);
        pInformasiLayout.setHorizontalGroup(
            pInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInformasiLayout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel10)
                .addContainerGap(393, Short.MAX_VALUE))
        );
        pInformasiLayout.setVerticalGroup(
            pInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInformasiLayout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(263, 263, 263))
        );

        jTengah.add(pInformasi, "card5");

        jLabel11.setText("ABOUT");

        javax.swing.GroupLayout pAboutLayout = new javax.swing.GroupLayout(pAbout);
        pAbout.setLayout(pAboutLayout);
        pAboutLayout.setHorizontalGroup(
            pAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAboutLayout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(384, 384, 384))
        );
        pAboutLayout.setVerticalGroup(
            pAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAboutLayout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(227, 227, 227))
        );

        jTengah.add(pAbout, "card6");

        getContentPane().add(jTengah, java.awt.BorderLayout.CENTER);

        jAtas.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM INFORMASI AKADEMIK");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROGRAM STUDI TEKNIK INFORMATIKA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UP. FTIK UNMUL");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POSTTEST3/unmul1.png"))); // NOI18N

        jToolBar1.setRollover(true);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        bHome.setText("HOME");
        bHome.setFocusable(false);
        bHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bHome.setMaximumSize(new java.awt.Dimension(90, 60));
        bHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bHomeMouseClicked(evt);
            }
        });
        jPanel1.add(bHome);

        bProfil.setText("PROFIL");
        bProfil.setFocusable(false);
        bProfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bProfil.setMaximumSize(new java.awt.Dimension(90, 60));
        bProfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bProfilMouseClicked(evt);
            }
        });
        jPanel1.add(bProfil);

        bGaleri.setText("GALERI");
        bGaleri.setFocusable(false);
        bGaleri.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bGaleri.setMaximumSize(new java.awt.Dimension(90, 60));
        bGaleri.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bGaleri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bGaleriMouseClicked(evt);
            }
        });
        jPanel1.add(bGaleri);

        bInformasi.setText("INFORMASI");
        bInformasi.setFocusable(false);
        bInformasi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bInformasi.setMaximumSize(new java.awt.Dimension(90, 60));
        bInformasi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bInformasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bInformasiMouseClicked(evt);
            }
        });
        jPanel1.add(bInformasi);

        bAbout.setText("ABOUT");
        bAbout.setFocusable(false);
        bAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAbout.setMaximumSize(new java.awt.Dimension(90, 60));
        bAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAboutMouseClicked(evt);
            }
        });
        bAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAboutActionPerformed(evt);
            }
        });
        jPanel1.add(bAbout);

        jToolBar1.add(jPanel1);

        javax.swing.GroupLayout jAtasLayout = new javax.swing.GroupLayout(jAtas);
        jAtas.setLayout(jAtasLayout);
        jAtasLayout.setHorizontalGroup(
            jAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jAtasLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 533, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jAtasLayout.setVerticalGroup(
            jAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jAtasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jAtas, java.awt.BorderLayout.PAGE_START);

        jBawah.setBackground(new java.awt.Color(204, 204, 0));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Copyright@2017");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MODUL PRAKTIKUM PEMROGRAMAN VISUAL");

        javax.swing.GroupLayout jBawahLayout = new javax.swing.GroupLayout(jBawah);
        jBawah.setLayout(jBawahLayout);
        jBawahLayout.setHorizontalGroup(
            jBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBawahLayout.createSequentialGroup()
                .addContainerGap(420, Short.MAX_VALUE)
                .addGroup(jBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBawahLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(64, 64, 64)))
                .addGap(381, 381, 381))
        );
        jBawahLayout.setVerticalGroup(
            jBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBawahLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        getContentPane().add(jBawah, java.awt.BorderLayout.PAGE_END);

        jKanan.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jKananLayout = new javax.swing.GroupLayout(jKanan);
        jKanan.setLayout(jKananLayout);
        jKananLayout.setHorizontalGroup(
            jKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jKananLayout.setVerticalGroup(
            jKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        getContentPane().add(jKanan, java.awt.BorderLayout.LINE_END);

        jKiri.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jKiriLayout = new javax.swing.GroupLayout(jKiri);
        jKiri.setLayout(jKiriLayout);
        jKiriLayout.setHorizontalGroup(
            jKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jKiriLayout.setVerticalGroup(
            jKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        getContentPane().add(jKiri, java.awt.BorderLayout.LINE_START);

        jMenu2.setText("DATA");

        jMenuItem1.setText("INPUT DATA");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("CARI DATA");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("DATA YUDISIUM");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("LAPORAN");
        jMenuBar1.add(jMenu1);

        jMenu5.setText("KELUAR");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAboutActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void bProfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProfilMouseClicked
        pHome.setVisible(false);
        pProfil.setVisible(true);
        pGaleri.setVisible(false);
        pInformasi.setVisible(false);
        pAbout.setVisible(false);
    }//GEN-LAST:event_bProfilMouseClicked

    private void bHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHomeMouseClicked
        pHome.setVisible(true);
        pProfil.setVisible(false);
        pGaleri.setVisible(false);
        pInformasi.setVisible(false);
        pAbout.setVisible(false);
        pAbout.setVisible(false);
        pAbout.setVisible(false);
    }//GEN-LAST:event_bHomeMouseClicked

    private void bGaleriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bGaleriMouseClicked
        pHome.setVisible(false);
        pProfil.setVisible(false);
        pGaleri.setVisible(true);
        pInformasi.setVisible(false);
        pAbout.setVisible(false);
    }//GEN-LAST:event_bGaleriMouseClicked

    private void bInformasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bInformasiMouseClicked
        pHome.setVisible(false);
        pProfil.setVisible(false);
        pGaleri.setVisible(false);
        pInformasi.setVisible(true);
        pAbout.setVisible(false);
    }//GEN-LAST:event_bInformasiMouseClicked

    private void bAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAboutMouseClicked
        pHome.setVisible(false);
        pProfil.setVisible(false);
        pGaleri.setVisible(false);
        pInformasi.setVisible(false);
        pAbout.setVisible(true);
    }//GEN-LAST:event_bAboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LatihanBorderLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LatihanBorderLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LatihanBorderLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LatihanBorderLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LatihanBorderLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbout;
    private javax.swing.JButton bGaleri;
    private javax.swing.JButton bHome;
    private javax.swing.JButton bInformasi;
    private javax.swing.JButton bProfil;
    private javax.swing.JPanel jAtas;
    private javax.swing.JPanel jBawah;
    private javax.swing.JPanel jKanan;
    private javax.swing.JPanel jKiri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jTengah;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pAbout;
    private javax.swing.JPanel pGaleri;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pInformasi;
    private javax.swing.JPanel pProfil;
    // End of variables declaration//GEN-END:variables
}
