/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POSTTEST4;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Simbolon-PC
 */
public class FormPelanggan extends javax.swing.JFrame {
   
    
    /**
     * Creates new form FormPelanggan
     */
    public FormPelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfHp = new javax.swing.JTextField();
        tfBerat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sDiskon = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        rbReguler = new javax.swing.JRadioButton();
        rbExpress = new javax.swing.JRadioButton();
        bProses = new javax.swing.JButton();
        lPersen = new javax.swing.JLabel();
        tfTotalTarif = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taStruk = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        bUlangi = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("FORM PELANGGAN");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jPanel7.setBackground(new java.awt.Color(169, 234, 21));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No. HP");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Berat");

        tfNama.setText("Masukkan Nama Pengguna");
        tfNama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfNamaCaretUpdate(evt);
            }
        });

        tfHp.setText("Masukkan No. Handphone");
        tfHp.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfHpCaretUpdate(evt);
            }
        });
        tfHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfHpKeyPressed(evt);
            }
        });

        tfBerat.setText("0");
        tfBerat.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfBeratCaretUpdate(evt);
            }
        });
        tfBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBeratActionPerformed(evt);
            }
        });
        tfBerat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBeratKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kg");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Diskon");

        sDiskon.setBackground(new java.awt.Color(169, 234, 21));
        sDiskon.setForeground(new java.awt.Color(255, 255, 255));
        sDiskon.setMajorTickSpacing(10);
        sDiskon.setPaintLabels(true);
        sDiskon.setPaintTicks(true);
        sDiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sDiskonStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jenis Jasa");

        buttonGroup1.add(rbReguler);
        rbReguler.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rbReguler.setForeground(new java.awt.Color(255, 255, 255));
        rbReguler.setText("Regular");
        rbReguler.setOpaque(false);

        buttonGroup1.add(rbExpress);
        rbExpress.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rbExpress.setForeground(new java.awt.Color(255, 255, 255));
        rbExpress.setText("Express");
        rbExpress.setOpaque(false);

        bProses.setBackground(new java.awt.Color(255, 255, 255));
        bProses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/check.png"))); // NOI18N
        bProses.setText("Proses");
        bProses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bProsesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bProsesMouseExited(evt);
            }
        });
        bProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProsesActionPerformed(evt);
            }
        });

        lPersen.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        lPersen.setForeground(new java.awt.Color(255, 255, 255));
        lPersen.setText("50%");

        tfTotalTarif.setEditable(false);
        tfTotalTarif.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        tfTotalTarif.setForeground(new java.awt.Color(255, 0, 0));
        tfTotalTarif.setText("Rp 0");
        tfTotalTarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalTarifActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Tarif (Rp)");

        jLabel14.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("(*format angka dan wajib diisi)");

        jLabel15.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("(*wajib diisi)");

        jLabel16.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("(*format angka dan wajib diisi)");

        jLabel18.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("(*wajib diisi)");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addComponent(jLabel9)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(sDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lPersen))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(tfBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(tfHp, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(rbReguler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbExpress))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(tfTotalTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(bProses)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGap(4, 4, 4)
                .addComponent(tfHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbReguler)
                    .addComponent(rbExpress))
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTotalTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bProses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 158, 11));

        taStruk.setEditable(false);
        taStruk.setColumns(20);
        taStruk.setRows(5);
        jScrollPane1.setViewportView(taStruk);

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("STRUK");

        bUlangi.setBackground(new java.awt.Color(255, 255, 255));
        bUlangi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/refresh.png"))); // NOI18N
        bUlangi.setText("Ulangi");
        bUlangi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bUlangiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bUlangiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bUlangiMousePressed(evt);
            }
        });

        bKeluar.setBackground(new java.awt.Color(255, 255, 255));
        bKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/logout.png"))); // NOI18N
        bKeluar.setText("Keluar");
        bKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bKeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bKeluarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(bUlangi)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(bKeluar)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bUlangi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(bKeluar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(37, 131, 59));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM PELANGGAN");

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("\"KURIRI\"");

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jalan Batu Cermin, Sempaja, Samarinda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel11))
                            .addComponent(jLabel1))
                        .addGap(56, 56, 56)))
                .addGap(288, 288, 288))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(37, 131, 59));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Copyright@2017");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(418, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(396, 396, 396))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfNamaCaretUpdate
        if (tfNama.getText().length()== 0 || tfBerat.getText().equals("0")){
            bProses.setEnabled(false);
        }
        else if (tfNama.getText().length()!=0 && tfHp.getText().length()!=0 && tfBerat.getText().length()!=0){
            bProses.setEnabled(true);
        }
        
    }//GEN-LAST:event_tfNamaCaretUpdate

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tfNama.setText("");
        tfHp.setText("");
        tfBerat.setText("");
        tfTotalTarif.setText("");
        
    }//GEN-LAST:event_formWindowOpened

    private void tfHpCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfHpCaretUpdate
        if (tfHp.getText().length()== 0 ||  tfBerat.getText().equals("0")){
            bProses.setEnabled(false);
        }
        else if (tfNama.getText().length()!=0 && tfHp.getText().length()!=0 && tfBerat.getText().length()!=0){
            bProses.setEnabled(true);
        }
    }//GEN-LAST:event_tfHpCaretUpdate

    private void tfBeratCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfBeratCaretUpdate
        if (tfBerat.getText().length()== 0 || tfBerat.getText().equals("0")){
            bProses.setEnabled(false);
        }
        else if (tfNama.getText().length()!=0 && tfHp.getText().length()!=0 && tfBerat.getText().length()!=0){
            bProses.setEnabled(true);
        }
    }//GEN-LAST:event_tfBeratCaretUpdate

    private void tfBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBeratActionPerformed

    private void sDiskonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sDiskonStateChanged

          lPersen.setText(String.valueOf(sDiskon.getValue()) + "%");
    }//GEN-LAST:event_sDiskonStateChanged

    private void bUlangiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bUlangiMousePressed
        tfNama.setText("");
        tfHp.setText("");
        tfBerat.setText("");
        taStruk.setText("");
        buttonGroup1.clearSelection();
        tfTotalTarif.setText("");
        sDiskon.setValue(50);
    }//GEN-LAST:event_bUlangiMousePressed

    private void bKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKeluarMouseClicked
        System.exit(0);
        
    }//GEN-LAST:event_bKeluarMouseClicked

    private void bProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProsesActionPerformed

        
        float Diskonnya, Reguler=11500, Total=0, Berat, TotalDiskon;
        String Nama, NoHP, Jasa;
        
        Nama = tfNama.getText();
        NoHP = tfHp.getText();
        Berat = Float.parseFloat(tfBerat.getText());
        
        Diskonnya = Float.valueOf(sDiskon.getValue());
        
        
        
        if(rbReguler.isSelected()){
            Jasa = rbReguler.getText();
            TotalDiskon = Reguler * (Diskonnya/100) * Berat;
            Total = (Reguler * Berat) - TotalDiskon;
            
        }
        else if(rbExpress.isSelected()){
            Jasa = rbExpress.getText();
            TotalDiskon = (float) (Reguler * 1.5 * (Diskonnya/100) * Berat);
            Total = (float) ((Reguler * Berat* 1.5) - TotalDiskon);
        }
        else {
            JOptionPane.showMessageDialog(null, "Pilih Jenis Jasa Pengiriman Terlebih Dahulu","PERINGATAN", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        tfTotalTarif.setText("Rp "+Total);
        taStruk.setText("=======================================================\n"
                        + " Nama\t: "+Nama+
                        "\n No.HP\t: "+NoHP+
                        "\n Berat\t: "+Berat+" Kg"+
                        "\n Diskon\t: "+Diskonnya+" %"+
                        "\n Potongan\t: Rp "+TotalDiskon+
                        "\n Jenis Jasa\t: "+Jasa+
                        "\n Total\t: Rp "+Total+
                        "\n======================================================="+
                        "\n\n Terima Kasih\n Telah Menggunakan Jasa Kami"+
                        "\n\n\t\t                   CEO\n\t\tR.H. Kimebmen Simbolon\n\t\t            (1515015131)");
        
    }//GEN-LAST:event_bProsesActionPerformed

    private void tfHpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHpKeyPressed
        tfHp.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
            char karakter1 = e.getKeyChar();
            if(!((karakter1 >= '0') && (karakter1 <= '9')) || (karakter1 == '\b')){
                e.consume();
            }
            }
            
}); 
    }//GEN-LAST:event_tfHpKeyPressed

    private void tfBeratKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBeratKeyPressed
        tfBerat.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
            char karakter = e.getKeyChar();
            if(((karakter < '0') || (karakter > '9')) && (karakter != '.')){
                e.consume();
            }
            }
            
});
    }//GEN-LAST:event_tfBeratKeyPressed

    private void bKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKeluarMouseEntered
        bKeluar.setBackground(Color.RED);
        bKeluar.setForeground(Color.BLACK);
    }//GEN-LAST:event_bKeluarMouseEntered

    private void bKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKeluarMouseExited
        bKeluar.setBackground(Color.WHITE);
        bKeluar.setForeground(Color.BLACK);
    }//GEN-LAST:event_bKeluarMouseExited

    private void bUlangiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bUlangiMouseEntered
        bUlangi.setBackground(Color.GREEN);
        bUlangi.setForeground(Color.BLACK);
    }//GEN-LAST:event_bUlangiMouseEntered

    private void bUlangiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bUlangiMouseExited
        bUlangi.setBackground(Color.WHITE);
        bUlangi.setForeground(Color.BLACK);
    }//GEN-LAST:event_bUlangiMouseExited

    private void bProsesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProsesMouseEntered
        bProses.setBackground(Color.GREEN);
        bProses.setForeground(Color.BLACK);
    }//GEN-LAST:event_bProsesMouseEntered

    private void bProsesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProsesMouseExited
        bProses.setBackground(Color.WHITE);
        bProses.setForeground(Color.BLACK);
    }//GEN-LAST:event_bProsesMouseExited

    private void tfTotalTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalTarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalTarifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bProses;
    private javax.swing.JButton bUlangi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lPersen;
    private javax.swing.JRadioButton rbExpress;
    private javax.swing.JRadioButton rbReguler;
    private javax.swing.JSlider sDiskon;
    private javax.swing.JTextArea taStruk;
    private javax.swing.JTextField tfBerat;
    private javax.swing.JTextField tfHp;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTotalTarif;
    // End of variables declaration//GEN-END:variables
}
